### ISSUE TITLE
Deserializing SimpleListRepresentation drops embedded resources

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [JakeGinnivan/WebApi.Hal#103]
I am enjoying WebAPI.Hal but running into an issue deserializing SingleListRepresentation<T>. The issue is that I don't see any embedded resources when deserializing my representations. I then tried to modify one of the existing tests to see if it was something I did but I don't see it there either.

The test 'one_item_organisation_list_get_json_test' uses OrganisationListRepresentation which has one or two embedded resources. When serializing, the result looks like this:

``` json
{
  "_links": {
    "self": {
      "href": "/api/organisations"
    },
    "organisation": {
      "href": "/api/organisations/1"
    }
  },
  "_embedded": {
    "organisation": [
      {
        "Id": 1,
        "Name": "Org1",
        "_links": {
          "self": {
            "href": "/api/organisations/1"
          }
        }
      }
    ]
  }
}
```

but when deserializing by adding these lines to the test:

``` cs
byte[] data = Encoding.UTF8.GetBytes(serialisedResult);
MemoryStream memStream = new MemoryStream(data);
var result = mediaFormatter.ReadFromStream(type, memStream, Encoding.UTF8, null);
```

I get a null ResourceList property.

any ideas?

Thanks!

Henrik

**Comment by kbrichan** [comment]
I get the expected result when I insert your code from above into the test you mention. What version of WebApi.Hal are you running?

![image](https://cloud.githubusercontent.com/assets/3181394/7869015/1e6b8e6e-053d-11e5-9be7-c929c2cec001.png)

**Comment by kbrichan** [comment]
Wait, I see. Version 2.5.1, the latest, works properly. But 2.5.0 has a problem with the constructor of SimpleListRepresentation. The 1-param c-tor is called by the Newtonsoft JObject's ToObject method with a null for the list. If you want to stay on 2.5.0 instead of updating to 2.5.1, add this line of code to the end of SimpleListRepresentation's 1-param c-tor:

    if (list == null) ResourceList = new List<TResource>();

We haven't caught this problem yet because at least I don't have any use cases for PUTting or POSTing a SimpleListRepresentation. I only use it for GET. In other words, my PUT and POST payloads are not SimpleListReprentation-derived.

**Comment by panmanphil** [comment]
closing stale issue
