### ISSUE TITLE
ASP.NET 5

### ISSUE THREAD

**Issue by DoCode** [JakeGinnivan/WebApi.Hal#114]
What about ASP.NET 5 (vNEXT) support?

**Comment by Kodrafo** [comment]
I have the same question. I can't register the formatters.
Do you plan to support ASP.NET 5?

**Comment by wis3guy** [comment]
I haven't had the chance to look into this. At this point, i do not know what kind of changes are required. In case the impact is significant, we need to seriously evaluate wether it is worth porting or if we should start fresh.

Not a conclusive answer, but we are all swamped at the moment. To be continued ...

**Comment by thabart** [comment]
The two projects "WebApi.Hal" + "WebApi.Hal.Web" have been migrated to ASP.NET 5, except some UTs because some of them still need to be refactored :'(.
If you want to take a look & implement my changes, the sources can be fetched from this url : https://github.com/thabart/WebApi.Hal
In my opinion it's better to create an another GitHub solution which supports ASP.NET 5 or create a GIT branch.

The media-type formatters "HAL+JSON" & "XML+JSON" can be added into your Startup.cs like this :
```
            services.AddMvc(options =>
            {
                options.OutputFormatters.Add(new XmlHalMediaTypeOutputFormatter());
                options.OutputFormatters.Add(new JsonHalMediaTypeOutputFormatter());
            });
```
The sample project can be found here : https://github.com/thabart/WebApi.Hal/blob/master/src/WebApi.Hal.Web/Startup.cs
This solution has been implemented on my personnal project "SimpleIdentityServer" : https://github.com/thabart/SimpleIdentityServer

**Comment by RehanSaeed** [comment]
Would be great to have this released as a NuGet packge.

**Comment by GraemeF** [comment]
@thabart Could you make a PR? Maybe then @JakeGinnivan would merge it...

**Comment by Jetski5822** [comment]
netstandard1.6 is now available on this PR https://github.com/JakeGinnivan/WebApi.Hal/pull/138 - Let me know what you lot think.

**Comment by aerotog** [comment]
Since the .Net Standard change was merged, this issue can be closed.

**Comment by panmanphil** [comment]
closing stale issue
