### ISSUE TITLE
I am very new to HAL and have issue using it. 

### ISSUE THREAD

**Issue by velchev** [JakeGinnivan/WebApi.Hal#129]
trying to integrate hal into existing asp.net mvc webapi2 project.
I have wrapper object that is returne in every request from the api.

```
{
  "version": "1.0.0.0",
  "error": false,
  "message": "OK",
  "status": "200",
  "data": [
```

here in data is the payload from the api request (if there is payload).
I am trying to include hal only in that object. - so only in the nested object so the response of api call will look like this:

```
Request.CreateResponse(HttpStatusCode.OK, new JsonResponse2<ChallengeViewModel>(resultViewModel));
[DataContract]
    public class JsonResponse2<T> where T : Representation
    {
        private MessageCode _messageCode;
        private string _messageString;

        public MessageCode MessageCode { get { return _messageCode; } }

        /// <summary>
        /// The version of the API
        /// </summary>
        /// <value>
        /// The version.
        /// </value>
        [DataMember(Name = "version")]
        public string Version
        {
.....
  [DataMember(Name = "data")]
        public T Data
        {
            get { return data; }
            private set { data = value; }
        }

```

What is happening when searalizing data in the output is that I do not have the fields from hal serialized.
when I return data as 
`return Request.CreateResponse(HttpStatusCode.OK, resultViewModel);` - without the wrapper around everything is good. Look at the library but do not want to change it if what I am missing is something very simple... 

Here is the Representation I am trying to return 

```
  [DataContract]
    public class ChallengeViewModel : Representation
    {
      [DataMember]
        public Guid Id { get; set; }

       [DataMember]
        public Guid CompetitionId { get; set; }

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "requiredRank")]
        public int RequiredRank { get; set; }

        [DataMember(Name = "totalEntries")]
        public int TotalEntrants { get; set; }

        [DataMember(Name = "type")]
        public Guid ChallengeTypeId { get; set; }

        public override string Rel
        {
            get { return LinkTemplates.Configurations.Challenge.Rel; }
            set { }
        }
        public override string Href
        {
            get { return LinkTemplates.Configurations.Challenge.CreateLink(new { id = Id }).Href; }
            set { }
        }

        protected override void CreateHypermedia()
        {
            Links.Add(LinkTemplates.Configurations.GameConfig.CreateLink(new { id = Id }));
        }
    }
```

As I said works fine without the wrapper class in which I set some generic staff for each response.
JsonProperty and DataMember is just a change for testing usually is only DataMember where just defining serialization.

**Comment by velchev** [comment]
What I noticed in this case is that when nested the class that inherits the representation class never gets called. (the code below never gets executed)
```
  [OnSerializing]
        private void OnSerialize(StreamingContext context)
        {
```

**Comment by wis3guy** [comment]
@velchev What you are trying to accomplish is not supported by the library out of the box. In order to get what you want, you would have to write your own MediaTypeFormatter which wraps the serialized representation in your wrapper object. Have a look at our tests to see how you could invoke our serializer to achieve that.

Please note that, the response you are trying to generate, is **not** a valid HAL response. The media type dictates a certain format for serialized responses. Where your plan fails it that it dictates that f.ex. links must be in the root of a resource.

I would recommend you create custom class, which derives from representation, that has the properties you are attempting to wrap around the HAL response. You would **not** have a `data` property, but all other properties could be on all your responses. That way, your response is valid HAL and can be consumed by a HAL compatible client.

Just my 2 cents ...
