### ISSUE TITLE
Links not serialized as a JSON collection

### ISSUE THREAD

**Issue by DrinqUp** [JakeGinnivan/WebApi.Hal#71]
The JSON output of the Links collection is not represented as a collection. Instead, it looks something like:
	"_links": {
		"self": {
			"href": "api/myresource"
		},
		"related1": {
			"href": "api/myfirstrelatedresource"
		},
		"related2": {
			"href": "api/mysecondrelatedresource"
		}
	}

**Comment by ttarney** [comment]
I have the same issue.  Exception:
{"Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.IList`1[WebApi.Hal.Link]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath '_links.participants', line 1, position 26."}

**Comment by panmanphil** [comment]
This is a HAL client then, written in .net, consuming json created by this api?

It's not inconceivable that this is a regression, and it is definitely a supported scenario. 

A simple sample demonstrating the problem would be great, or a failing test we could put in the suite even better.

**Comment by saday-cimpress** [comment]
Same issue here with the Links.self property.

An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[WebApi.Hal.Link]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

Path '_links.self', line 1, position 126.

WebApi.Hal 2.6.0
Newtonsoft.Json 8.0.3
RestSharp 105.2.3

And the scrubbed line of code:
Foo myObj = JsonConvert.DeserializeObject<Foo>(response.Content);

**Comment by CarlosTorrecillas** [comment]
I have the same issue than @saday-cimpress .

WebApi.Hal 2.6.0
Newtonsoft.Json 6.0.8
RestSharp 105.0.1

**Comment by CarlosTorrecillas** [comment]
I found a workaround here if you want to get back your representation: https://github.com/JakeGinnivan/WebApi.Hal/issues/125

**Comment by saday-cimpress** [comment]
My workaround was to just use JObject and throw away the links.  Defeats the point, but it works.

**Comment by kbrichan** [comment]
The serialized hal+json is intended to be read by a hal+json deserializer. If you're using an ordinary json deserializer, like Newtonsoft.Json, it will not work right. Use a client aware of hal+json, as described in #125
