### ISSUE TITLE
Question: create link with multiple parameters

### ISSUE THREAD

**Issue by Unrefraction** [JakeGinnivan/WebApi.Hal#99]
Hi everyone,
I have the next relative link "/alerts{?continuationToken}{&startTime}{&endTime}". All parameters are optional, so user can provide only, for example, 'endTime' and expects to get /alerts?endTime=value with the response.

Unfortunately, when I call CreateLink and pass 'new { endTime = value }' object, I get '/alerts&endTime=value' (which is expected due to my template), but Asp.Net doesn't recognize this parameter and throws an error when I do request '/alerts&endTime=2014-07-30'
A potentially dangerous Request.Path value was detected from the client

Is there any way to construct such templates with random number of parameters in an easier way without appending them manually?

**Comment by JakeGinnivan** [comment]
Possible that the UriTemplate class could be made smarter to correct this. You could give it a go in a pull request?

**Comment by wis3guy** [comment]
@unrefraction: So is your issue the ampersand? If so, it is caused by the way you constructed your template. The class' implementation is based on this specification: http://xml.coverpages.org/draft-gregorio-uritemplate-04.txt (not sure the version matches). Your template should read:
~~~
/alerts{?continuationToken,startTime,endTime}
~~~
The class is smart enough to decide what separator (? or &) to use at what point in the resulting uri.

Also, i would pass your dates as a single numeric value, in my experience, that is easier to deal with (no formatting/order issues). You could use Unix Timestamp formats. The following link points to some useful helper methods i (re)use frequently: http://stackoverflow.com/questions/249760/how-to-convert-unix-timestamp-to-datetime-and-vice-versa

**Comment by Unrefraction** [comment]
@wis3guy,
Thanks for your template example. This is what I was looking for, thank you!
